#############################################################
# Dockerfile para instalar ansible y ejecutar menú LDT
# Basado en Ubuntu
# Con Expose ponemos a la escucha al puerto 12345
#############################################################

FROM ubuntu:latest

MAINTAINER JuanAFernandez juanantc mortega87 rubenadrados JA-Gonz

#Ejecutar script de instalación

ADD https://github.com/freelinuxdistrodeployed/LDT/blob/master/install.sh ./install.sh
CMD ["/bin/bash", "/install.sh"]

#Ejecutar menú LDT
ADD https://github.com/freelinuxdistrodeployed/LDT/blob/master/LDT.sh /LDT.sh
CMD ["/bin/bash", "/LDT.sh"]

EXPOSE 12345
