#!/bin/bash
#Script para notificaciones mediante ventanas emergentes

MENSAJE_ENVIADO=0
while [ $MENSAJE_ENVIADO -le 1 ]; do # Mientras mensaje sea menor que 1 ejecutar buclue (se pondrá a 1 cuando el mensaje haya sido enviado)
	echo "Introduzca el mensaje"	
	read MENSAJE
	if [ -n "$MENSAJE" ]; then #Hay un mensaje a enviar
		ansible all -a "notify-send "$MENSAJE"
		MENSAJE_ENVIADO=2		
	else	#El mensaje está vacío
		echo "¿Dónde está el mensaje?"
	fi
done
